solution
mate-academy/js_array-method-sort pull request #1285
Opened 2023-06-07 15:28 UTC by AndriiYelieva

2023-06-07 15:57 UTC, Viktor-Kost requested changes

2023-06-07 15:57 UTC, Viktor-Kost commented on src/arrayMethodSort.js
> +            : String(this[i]) > String(this[j])
It's better to create a default comparing function outside applyCustomSort function and set it as a default value

Example: 
```
const compareAsString = (a, b) => {
...
}

...

[].__proto__.sort2 = function(compareFunction = compareAsString) {
...
```

2023-06-10 08:08 UTC, etojeDenys requested changes
it will improve readability

2023-06-10 08:08 UTC, etojeDenys commented on src/arrayMethodSort.js
> +      count = 0;
we can use a boolean variable here

2023-06-10 08:08 UTC, etojeDenys commented on src/arrayMethodSort.js
> +          count++;
set here to true

2023-06-10 08:08 UTC, etojeDenys commented on src/arrayMethodSort.js
> +    } while (count > 0);
and check if true here

2023-06-13 10:23 UTC, IvanFesenko requested changes

2023-06-13 10:23 UTC, IvanFesenko commented on src/arrayMethodSort.js
> +    for (let i = 0; i < this.length - 1; i++) {
Create separate `sortString` that will be used if no `compareFunction` 

```suggestion
  [].__proto__.sort2 = function(compareFunction  = sortString) {
    // write code here
    for (let i = 0; i < this.length - 1; i++) {
```

2023-06-13 10:23 UTC, IvanFesenko commented on src/arrayMethodSort.js
> +          : String(this[j]) > String(this[j + 1]);
```suggestion
        const shouldSwap = compareFunction(this[j], this[j + 1]) > 0;
```

2024-09-12 11:17 UTC, closed without merging