Solution
mate-academy/js_array-method-sort pull request #1300
Opened 2023-06-16 17:31 UTC by rvrazovskyi

2023-06-16 18:54 UTC, PolinaRomanenko requested changes
look at the comments

2023-06-16 18:54 UTC, PolinaRomanenko commented on src/arrayMethodSort.js
> +      return Array.prototype.sort.call(this);
Instead of returning the native Array.prototype.sort, implement a custom sorting method without a compareFunction.

2023-06-16 18:54 UTC, PolinaRomanenko commented on src/arrayMethodSort.js
> +      return Array.prototype.sort.call(this, compareFunction);
Instead of returning the native Array.prototype.sort, implement a custom sorting method.

2023-06-16 18:54 UTC, PolinaRomanenko commented on src/arrayMethodSort.js
> +      return Array.prototype.sort.call(this, compareFunction);
A helper function to compare two elements should be created and used

2023-06-18 09:54 UTC, VeronikaSynieokaia approved these changes

2023-06-18 09:58 UTC, VeronikaSynieokaia approved these changes

2023-06-18 09:59 UTC, VeronikaSynieokaia commented
good job

2023-06-18 09:59 UTC, closed without merging