solution
mate-academy/js_array-method-sort pull request #213
Opened 2021-02-18 15:46 UTC by yashnyi

2021-02-19 09:12 UTC, SofiiaAsieieva approved these changes
:fire:

2021-02-19 09:15 UTC, Vladimir-Beliy requested changes

2021-02-19 09:15 UTC, Vladimir-Beliy commented on src/arrayMethodSort.js
> +  [].__proto__.sort2 = function(compareFunction = (value1, value2) => {
плохая идея объявлять функцию прам в аргументах

2021-02-23 14:54 UTC, solaryasha requested changes

2021-02-23 14:54 UTC, solaryasha commented on src/arrayMethodSort.js
> +        const prev = this[i - 1];
Не скорочуй назви змінних.

2021-02-23 14:54 UTC, solaryasha commented on src/arrayMethodSort.js
> +    let count;
Давай зробимо цю змінну булевого типу, hasChanged наприклад.

2021-02-23 16:41 UTC, solaryasha approved these changes

2025-09-01 20:49 UTC, closed without merging