Solution
mate-academy/js_array-method-sort pull request #764
Opened 2022-08-22 20:52 UTC by MihailKostov

2022-08-27 11:45 UTC, SanyaBratashchuk requested changes

2022-08-27 11:45 UTC, SanyaBratashchuk commented on src/arrayMethodSort.js
> +  const sortMethod = (a, b) => {
```suggestion
  const defaultCompareFunction = (a, b) => {
```

2022-08-27 11:45 UTC, SanyaBratashchuk commented on src/arrayMethodSort.js
> +        : -1;
Don't use nested ternary operators. It is hard to read

2022-08-29 10:59 UTC, MihailKostov commented
So is it better to use ternary operators or operator If?

2022-08-30 15:01 UTC, valerii-derkach approved these changes

2022-08-30 15:01 UTC, valerii-derkach commented on src/arrayMethodSort.js
> +    }
```suggestion
    if (stringA > stringB) {
      return 1;
    } 
    if (stringA < stringB) {
      return -1;
    } 
    return 0;
```

2026-03-23 18:32 UTC, closed without merging