implement sort function
mate-academy/js_array-method-sort pull request #825
Opened 2022-09-22 17:36 UTC by SerhiiRomaniukWD

2022-09-22 17:59 UTC, oleksandr-korobko approved these changes
Good Job!!!

2022-09-26 16:48 UTC, naziamoff requested changes

2022-09-26 16:48 UTC, naziamoff commented on src/arrayMethodSort.js
> +  [].__proto__.sort2 = function(compareFunction = copmareAsStrings) {
```suggestion
  [].__proto__.sort2 = function(compareFunction = compareAsStrings) {
```

2022-09-27 14:41 UTC, naziamoff approved these changes
🔥

2025-05-25 17:22 UTC, closed without merging